#!/usr/bin/env bash
# ============================================================================
# LifeLedger Home Assistant Add-on — Entrypoint
# ============================================================================
# Reads options from the HA Supervisor options API, writes a runtime
# lifeledger_config.yaml, and starts the uvicorn server.
# ============================================================================

set -euo pipefail

CONFIG_DIR="/config"
APP_DIR="/app"
CONFIG_FILE="${CONFIG_DIR}/lifeledger_config.yaml"
LOG_FILE="${CONFIG_DIR}/lifeledger.log"
DB_FILE="${CONFIG_DIR}/lifeledger.db"

# ── Read HA options ────────────────────────────────────────────────────────
LOG_LEVEL=$(bashio::config 'log_level' 'INFO')
BASE_CURRENCY=$(bashio::config 'base_currency' 'GBP')
PROJ_START=$(bashio::config 'projection_start_year' '2025')
PROJ_END=$(bashio::config 'projection_end_year' '2075')
INFLATION=$(bashio::config 'inflation_base_rate' '0.025')
MC_SIMS=$(bashio::config 'monte_carlo_simulations' '1000')
MC_SEED=$(bashio::config 'monte_carlo_seed' '42')
DRIVE_ENABLED=$(bashio::config 'drive_sync_enabled' 'false')
DRIVE_INTERVAL=$(bashio::config 'drive_sync_interval_minutes' '5')

bashio::log.info "LifeLedger: starting (log_level=${LOG_LEVEL}, currency=${BASE_CURRENCY})"

# ── Create data directories ──────────────────────────────────────────────────
mkdir -p "${CONFIG_DIR}/scenarios" \
         "${CONFIG_DIR}/scenarios/templates" \
         "${CONFIG_DIR}/checkpoints" \
         "${CONFIG_DIR}/exports"

# ── Copy built-in scenario templates if not already present ──────────────────
TEMPLATES_SRC="${APP_DIR}/data/scenarios/templates"
TEMPLATES_DST="${CONFIG_DIR}/scenarios/templates"
if [ -d "${TEMPLATES_SRC}" ]; then
    for f in "${TEMPLATES_SRC}"/*.yaml; do
        dst="${TEMPLATES_DST}/$(basename "$f")"
        if [ ! -f "${dst}" ]; then
            cp "${f}" "${dst}"
            bashio::log.info "Installed template: $(basename "$f")"
        fi
    done
fi

# ── Write runtime config ──────────────────────────────────────────────────────
cat > "${CONFIG_FILE}" << YAML_EOF
# LifeLedger — Runtime config (generated by HA add-on, do not edit manually)
# Edit via Home Assistant Add-on Options panel.

app:
  name: "LifeLedger"
  version: "1.0.0"
  base_currency: "${BASE_CURRENCY}"
  log_level: "${LOG_LEVEL}"
  log_file: "${LOG_FILE}"
  log_to_console: true
  log_to_file: true

projection:
  start_year: ${PROJ_START}
  end_year: ${PROJ_END}
  time_step: annual

inflation:
  base_rate: ${INFLATION}
  low_rate: 0.015
  high_rate: 0.040
  periods: []

fx:
  rates:
    GBP_USD: 1.27
    GBP_EUR: 1.17
  annual_drift:
    GBP_USD: 0.0
    GBP_EUR: 0.0

monte_carlo:
  enabled: true
  simulations: ${MC_SIMS}
  seed: ${MC_SEED}
  growth_std_dev: 0.12
  inflation_std_dev: 0.005
  sequence_of_returns_risk: true
  crash_window_years: 5

drive:
  enabled: ${DRIVE_ENABLED}
  sync_on_save: true
  auto_sync_interval_minutes: ${DRIVE_INTERVAL}
  folder_name: "LifeLedger"
  conflict_resolution: "prompt"

database:
  path: "${DB_FILE}"
  cache_market_prices: true
  price_staleness_hours: 24

engine:
  income_auto_adds_to_networth: false
  checkpoint_boundary: true
YAML_EOF

bashio::log.info "LifeLedger: config written to ${CONFIG_FILE}"

# ── Set environment for the Python app ───────────────────────────────────────
export LIFELEDGER_CONFIG="${CONFIG_FILE}"
export LIFELEDGER_DB="${DB_FILE}"
export LIFELEDGER_LOG="${LOG_FILE}"
export PYTHONPATH="${APP_DIR}:${PYTHONPATH:-}"

# ── Start uvicorn ──────────────────────────────────────────────────────────
bashio::log.info "LifeLedger: starting uvicorn on port 8000"
exec python -m uvicorn backend.main:app \
    --host 0.0.0.0 \
    --port 8000 \
    --log-level "$(echo "${LOG_LEVEL}" | tr '[:upper:]' '[:lower:]')" \
    --workers 1 \
    --no-access-log
