#!/usr/bin/env bash
# ============================================================================
# LifeLedger Home Assistant Add-on — Entrypoint
# ============================================================================
# HA Supervisor writes add-on options to /data/options.json.
# This script reads them with Python (no bashio dependency needed),
# writes a runtime lifeledger_config.yaml, and starts uvicorn.
# ============================================================================

set -euo pipefail

APP_DIR="/app"
CONFIG_DIR="/config"       # HA bind-mounts /config here (map: config:rw)
DATA_DIR="/data"           # HA internal add-on data directory
OPTIONS_FILE="${DATA_DIR}/options.json"

CONFIG_FILE="${CONFIG_DIR}/lifeledger_config.yaml"
LOG_FILE="${CONFIG_DIR}/lifeledger.log"
DB_FILE="${CONFIG_DIR}/lifeledger.db"

echo "[LifeLedger] Add-on starting..."

# ── Read options from /data/options.json ──────────────────────────────────────
# HA Supervisor writes this file from the options the user sets in the UI.
# We use Python to extract values so we don't need bashio.
read_option() {
    local key="$1"
    local default="$2"
    python3 -c "
import json, sys
try:
    with open('${OPTIONS_FILE}') as f:
        d = json.load(f)
    print(d.get('${key}', '${default}'))
except Exception:
    print('${default}')
"
}

LOG_LEVEL=$(read_option log_level INFO)
BASE_CURRENCY=$(read_option base_currency GBP)
PROJ_START=$(read_option projection_start_year 2025)
PROJ_END=$(read_option projection_end_year 2075)
INFLATION=$(read_option inflation_base_rate 0.025)
MC_SIMS=$(read_option monte_carlo_simulations 1000)
MC_SEED=$(read_option monte_carlo_seed 42)
DRIVE_ENABLED=$(read_option drive_sync_enabled false)
DRIVE_INTERVAL=$(read_option drive_sync_interval_minutes 5)

echo "[LifeLedger] log_level=${LOG_LEVEL}  currency=${BASE_CURRENCY}  MC_sims=${MC_SIMS}"

# ── Create directories in /config (persisted across restarts) ─────────────────
mkdir -p \
    "${CONFIG_DIR}/scenarios" \
    "${CONFIG_DIR}/scenarios/templates" \
    "${CONFIG_DIR}/checkpoints" \
    "${CONFIG_DIR}/exports"

# ── Copy bundled scenario templates if not already present ───────────────────
TEMPLATES_SRC="${APP_DIR}/data/scenarios/templates"
TEMPLATES_DST="${CONFIG_DIR}/scenarios/templates"
if [ -d "${TEMPLATES_SRC}" ]; then
    for f in "${TEMPLATES_SRC}"/*.yaml; do
        [ -f "${f}" ] || continue
        dst="${TEMPLATES_DST}/$(basename "${f}")"
        if [ ! -f "${dst}" ]; then
            cp "${f}" "${dst}"
            echo "[LifeLedger] Installed template: $(basename "${f}")"
        fi
    done
fi

# ── Write runtime lifeledger_config.yaml ──────────────────────────────────────
cat > "${CONFIG_FILE}" << YAML_EOF
# LifeLedger runtime config — generated by HA add-on
# Edit options via the Home Assistant Add-on Configuration tab.
# This file is regenerated on each add-on restart.

app:
  name: "LifeLedger"
  version: "1.0.0"
  base_currency: "${BASE_CURRENCY}"
  log_level: "${LOG_LEVEL}"
  log_file: "${LOG_FILE}"
  log_to_console: true
  log_to_file: true

projection:
  start_year: ${PROJ_START}
  end_year: ${PROJ_END}
  time_step: annual

inflation:
  base_rate: ${INFLATION}
  low_rate: 0.015
  high_rate: 0.040
  periods: []

fx:
  rates:
    GBP_USD: 1.27
    GBP_EUR: 1.17
  annual_drift:
    GBP_USD: 0.0
    GBP_EUR: 0.0

monte_carlo:
  enabled: true
  simulations: ${MC_SIMS}
  seed: ${MC_SEED}
  growth_std_dev: 0.12
  inflation_std_dev: 0.005
  sequence_of_returns_risk: true
  crash_window_years: 5

drive:
  enabled: ${DRIVE_ENABLED}
  sync_on_save: true
  auto_sync_interval_minutes: ${DRIVE_INTERVAL}
  folder_name: "LifeLedger"
  conflict_resolution: "prompt"

database:
  path: "${DB_FILE}"
  cache_market_prices: true
  price_staleness_hours: 24

engine:
  income_auto_adds_to_networth: false
  checkpoint_boundary: true

# Paths — point the app at /config so user data persists across restarts
paths:
  scenarios: "${CONFIG_DIR}/scenarios"
  checkpoints: "${CONFIG_DIR}/checkpoints"
  exports: "${CONFIG_DIR}/exports"
YAML_EOF

echo "[LifeLedger] Config written to ${CONFIG_FILE}"

# ── Environment ───────────────────────────────────────────────────────────────
export LIFELEDGER_CONFIG="${CONFIG_FILE}"
export LIFELEDGER_DB="${DB_FILE}"
export LIFELEDGER_LOG="${LOG_FILE}"
export PYTHONPATH="${APP_DIR}:${PYTHONPATH:-}"

# ── Start uvicorn ─────────────────────────────────────────────────────────────
echo "[LifeLedger] Starting on port 8000..."
exec python3 -m uvicorn backend.main:app \
    --host 0.0.0.0 \
    --port 8000 \
    --log-level "$(echo "${LOG_LEVEL}" | tr '[:upper:]' '[:lower:]')" \
    --workers 1 \
    --no-access-log
